### ISSUE TITLE
WCString type

### ISSUE THREAD

**Issue by cookiengineer** [TooTallNate/ref-wchar#2]
Is this line a typo?

https://github.com/TooTallNate/ref-wchar/blob/master/index.js#L63

I'm asking that because node-ffi throws an unkown ffi_type error on Linux:

``` bash
AssertionError: Could not determine the `ffi_type` instance for type: WCString
```

**Comment by TooTallNate** [comment]
No, but what's happening is probably you have multiple instances of `ref` installed. This module kinda depends on sharing the same `ref` instance that `node-ffi` uses, since node-ffi rudely monkey-patches `ref.types` with the `ffi_type` instances. Try going through your node_modules and making sure that only one copy is being used (look into `npm dedup` command).

**Comment by cookiengineer** [comment]
Thanks for the hint! That solved the problems!
